version: '2.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ~/grafana-mongo:/data/db

  mongo-proxy:
    build:
      context: .
      dockerfile: ProxyDockerfile
    restart: always

  grafana:
    env_file: configuration.env
    build:
      context: .
      dockerfile: GrafanaDockerfile
    restart: always
    ports:
      - 3000:3000