version: '2.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_usr}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_pwd}
    volumes:
      - /var/data/grafamo:/data/db

  middleware:
    build:
      context: .
      dockerfile: ProxyDockerfile
    restart: always

  grafana:
    env_file: configuration.env
    build:
      context: .
      dockerfile: GrafanaDockerfile
    restart: always
    ports:
      - 3000:3000